### ISSUE TITLE
pip install json-rpc breaks pyls installation

### ISSUE THREAD

**Issue by joaotavora** [pavlov99/json-rpc#103]
After installing with `pip install json-rpc` my installation of [pyls](https://github.com/palantir/python-language-server) broke.  I had installed it with `pip install 'python-language-server[all]'`.

Here's what I get:

```
❯❯❯ pip install json-rpc
Collecting json-rpc
  Using cached https://files.pythonhosted.org/packages/d2/c1/4795383bbce585fc376be66ad54cf670543a5c3349783c8a520d5a6402bd/json_rpc-1.11.1-py2.py3-none-any.whl
Installing collected packages: json-rpc
Successfully installed json-rpc-1.11.1
❯❯❯ pyls 
Traceback (most recent call last):
  File "/home/capitaomorte/holy/bin/local/pyls", line 6, in <module>
    from pyls.__main__ import main
  File "/home/capitaomorte/.local/lib/python3.7/site-packages/pyls/__main__.py", line 7, in <module>
    from .python_ls import start_io_lang_server, start_tcp_lang_server, PythonLanguageServer
  File "/home/capitaomorte/.local/lib/python3.7/site-packages/pyls/python_ls.py", line 7, in <module>
    from jsonrpc.endpoint import Endpoint
  File "/home/capitaomorte/.local/lib/python3.7/site-packages/jsonrpc/endpoint.py", line 7, in <module>
    from .exceptions import JsonRpcException, JsonRpcRequestCancelled, JsonRpcInternalError, JsonRpcMethodNotFound
ImportError: cannot import name 'JsonRpcException' from 'jsonrpc.exceptions' (/home/capitaomorte/.local/lib/python3.7/site-packages/jsonrpc/exceptions.py)
```

This is with
```
 ❯❯❯ python --version                                                                                                                   master ◼
Python 3.7.2rc1
```

I'm using system python, no version managers, installed with
```
apt install python3
```
Should I use a python version manager? _Must_ I for these two packages to coexist?

**Comment by pavlov99** [comment]
@joaotavora I could confirm that json-rpc breaks `python-language-server[all]`.

This is because it uses another package https://github.com/palantir/python-jsonrpc-server with the same `jsonrpc` module name. Let me see how could this be fixed.

**Comment by pavlov99** [comment]
Hi, @joaotavora 

`python-jsonrpc-server` maintainer has kindly renamed the package and now there should not be conflicts. Please let me know if you experience otherwise.

Closing the issue.
