### ISSUE TITLE
Fails to return null

### ISSUE THREAD

**Issue by solorab** [pavlov99/json-rpc#23]
I want to return null as a result. I expect like `{"jsonrpc": "2.0", "result": null, "id": 0}`, but it throws exceptions: `ValueError: Either result or error should be used` and `UnboundLocalError: local variable 'output' referenced before assignment`.
I think the reason is that it takes `None` as *not defined* and ignores `null`.
Would you correct this problem?

Example code:

``` python
from jsonrpc import JSONRPCResponseManager, dispatcher

dispatcher["nop"] = lambda: None

data = '{"jsonrpc": "2.0", "method": "nop", "params": [], "id": 0}'
JSONRPCResponseManager.handle(data, dispatcher)
```

This prints (python3.4):

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/json_rpc-1.8.0-py3.4.egg/jsonrpc/manager.py", line 119, in _get_responses
  File "/usr/local/lib/python3.4/dist-packages/json_rpc-1.8.0-py3.4.egg/jsonrpc/manager.py", line 96, in response
  File "/usr/local/lib/python3.4/dist-packages/json_rpc-1.8.0-py3.4.egg/jsonrpc/base.py", line 62, in __init__
ValueError: Either result or error should be used

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "foo.py", line 6, in <module>
    JSONRPCResponseManager.handle(data, dispatcher)
  File "/usr/local/lib/python3.4/dist-packages/json_rpc-1.8.0-py3.4.egg/jsonrpc/manager.py", line 58, in handle
  File "/usr/local/lib/python3.4/dist-packages/json_rpc-1.8.0-py3.4.egg/jsonrpc/manager.py", line 74, in handle_request
  File "/usr/local/lib/python3.4/dist-packages/json_rpc-1.8.0-py3.4.egg/jsonrpc/manager.py", line 74, in <listcomp>
  File "/usr/local/lib/python3.4/dist-packages/json_rpc-1.8.0-py3.4.egg/jsonrpc/manager.py", line 122, in _get_responses
UnboundLocalError: local variable 'output' referenced before assignment
```

**Comment by pavlov99** [comment]
Information was not added to the issue, closed as outdated.
