### ISSUE TITLE
output is referenced before assignment error

### ISSUE THREAD

**Issue by pavlov99** [pavlov99/json-rpc#29]
If function does not return output, django manager returns 500 error: reference before assignment.

Function:
```python
def echo(request=None, text=None):
    send_mail(text)
```

default django client is used. Request:
```javascript
{jsonrpc: "2.0", id: "0", method: "echo", params: {text: "My text"}}
```

Server response:
```python
Traceback (most recent call last):
  File "~/.env/lib/python3.4/site-packages/django/contrib/staticfiles/handlers.py", line 64, in __call__
    return self.application(environ, start_response)
  File "~/.env/lib/python3.4/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    response = self.get_response(request)
  File "~/.env/lib/python3.4/site-packages/django/core/handlers/base.py", line 199, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "~/.env/lib/python3.4/site-packages/django/core/handlers/base.py", line 236, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "~/.env/lib/python3.4/site-packages/django_extensions/management/technical_response.py", line 5, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "~/.env/lib/python3.4/site-packages/six.py", line 659, in reraise
    raise value
  File "~/.env/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "~/.env/lib/python3.4/site-packages/jsonrpc/backend/django.py", line 52, in jsonrpc
    jsonrpc_request, self.dispatcher)
  File "~/.env/lib/python3.4/site-packages/jsonrpc/manager.py", line 75, in handle_request
    responses = [r for r in cls._get_responses(rs, dispatcher)
  File "~/.env/lib/python3.4/site-packages/jsonrpc/manager.py", line 75, in <listcomp>
    responses = [r for r in cls._get_responses(rs, dispatcher)
  File "~/.env/lib/python3.4/site-packages/jsonrpc/manager.py", line 129, in _get_responses
    yield output
UnboundLocalError: local variable 'output' referenced before assignment
```

Quickfix:
```python
def echo(request=None):
    send_mail()
    return ""
```

**Comment by pavlov99** [comment]
+ @prawn-cake seems bug was reproduced.

**Comment by nikitinsm** [comment]
+1 Да баг кроется в JSONRPC10Response/JSONRPC20Response 

Вот тут: 
```
@result.setter
    def result(self, value):
        if value is not None:
            if self.error is not None:
                raise ValueError("Either result or error should be used")

            self._data["result"] = value
```

Так как все происходит внутри генератора, то попытка выйти из него приводит видимо к переходу на yield, а там output еще не существует, самое веселое статический анализатор этого не покажет.

**Comment by tacone** [comment]
We still experience this issue intermittently with the latest version and as such we cannot use this library in production. Initializing the variable `output` fixes the problem.

I will send a PR, please merge it and tag a new version.
